"""Generate the Music wordmark with a clearly recognizable s."""

from pathlib import Path
import shutil
import subprocess
import tempfile

from fontTools.pens.transformPen import TransformPen
from fontTools.pens.ttGlyphPen import TTGlyphPen
from fontTools.ttLib import TTFont


root = Path(__file__).resolve().parents[2]
source = root / "firmware/assets/fonts/Lobster-Regular.ttf"
output = root / "firmware/src/ui/assets/azoria_font_music_38.c"

with tempfile.TemporaryDirectory(prefix="azoria-music-") as directory:
    derived = Path(directory) / "Azoria-Music.ttf"
    font = TTFont(source)
    glyphs = font.getGlyphSet()
    pen = TTGlyphPen(glyphs)
    # Keep the lowercase advance and baseline, but use the font's two-curve S
    # scaled to the lowercase height instead of the triangular script s.
    glyphs["S"].draw(TransformPen(pen, (0.72, 0, 0, 0.72, 0, 0)))
    font["glyf"]["s"] = pen.glyph()
    # The original family name is reserved by the SIL Open Font License.
    for record in font["name"].names:
        if record.nameID in (1, 3, 4, 6, 16, 18, 21):
            name = "AzoriaMusic-Regular" if record.nameID == 6 else "Azoria Music"
            record.string = name.encode(record.getEncoding())
    font.save(derived)

    npx = shutil.which("npx.cmd") or shutil.which("npx")
    if not npx:
        raise SystemExit("Node.js / npx is required to generate the font")
    subprocess.run(
        [npx, "--yes", "lv_font_conv@1.5.3", "--size", "38", "--bpp", "4",
         "--format", "lvgl", "--font", str(derived), "--symbols", "Music",
         "--no-kerning", "--lv-include", "lvgl.h", "--lv-font-name",
         "azoria_font_music_38", "-o", str(output)],
        cwd=root, check=True,
    )

lines = output.read_text(encoding="utf-8").splitlines()
lines[3] = " * Generated by firmware/scripts/generate_music_font.py (SIL OFL 1.1)."
lines[1:1] = [
    " * Copyright 2010 The Lobster Project Authors.",
    " * Font data licensed under SIL OFL 1.1; see firmware/assets/fonts/OFL-Lobster.txt.",
]
output.write_text("\n".join(lines) + "\n", encoding="utf-8")
