"""Build the open-license numerals used by the Touch quota instrument."""
from pathlib import Path
import shutil
import subprocess
import tempfile
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

root = Path(__file__).resolve().parents[2]
source = root / "firmware/assets/fonts/RobotoCondensed/RobotoCondensed.ttf"
node = shutil.which("node")
converter = shutil.which("lv_font_conv")
if not node:
    raise SystemExit("Node.js is required")

with tempfile.TemporaryDirectory(prefix="yangci-usage-font-") as folder:
    instance = Path(folder) / "RobotoCondensed-Bold.ttf"
    instantiateVariableFont(TTFont(source), {"wght": 700}).save(instance)
    command = [converter] if converter else [shutil.which("npx.cmd") or shutil.which("npx"), "--yes", "lv_font_conv@1.5.3"]
    if not command[0]:
        raise SystemExit("lv_font_conv / npx is required")
    for size in [80, 110]:
        output = root / f"firmware/src/ui/assets/azoria_font_usage_{size}.c"
        subprocess.run(command + ["--size", str(size), "--bpp", "4", "--format", "lvgl", "--font", str(instance),
            "--symbols", "0123456789.%+-TBKM", "--no-kerning", "--lv-include", "lvgl.h",
            "--lv-font-name", f"azoria_font_usage_{size}", "--lv-fallback", "lv_font_montserrat_48", "-o", str(output)], check=True, cwd=root)
        lines = output.read_text(encoding="utf-8").splitlines()
        lines[3] = " * Generated by firmware/scripts/generate_usage_font.py; Roboto Condensed Bold, SIL OFL 1.1."
        lines[1:1] = [" * Copyright 2011 The Roboto Project Authors.", " * See firmware/assets/fonts/RobotoCondensed/OFL.txt."]
        output.write_text("\n".join(lines) + "\n", encoding="utf-8")
